// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpJ3D_A6FvWv3E4GReo8cuIIUrEo9aWLc',
    appId: '1:317216724501:web:15149d6c646db42e06601c',
    messagingSenderId: '317216724501',
    projectId: 'smart-roll-call-76a46',
    authDomain: 'smart-roll-call-76a46.firebaseapp.com',
    storageBucket: 'smart-roll-call-76a46.firebasestorage.app',
    measurementId: 'G-6C67YBB5JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MD4YFnfHyuXIUFMBCPl9M6-u1OIYK5g',
    appId: '1:317216724501:android:38ec0a8c918137be06601c',
    messagingSenderId: '317216724501',
    projectId: 'smart-roll-call-76a46',
    storageBucket: 'smart-roll-call-76a46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF1qEoNBVUtCFX07zoHpytvDoPz5KX554',
    appId: '1:317216724501:ios:178e9d2a0435a25f06601c',
    messagingSenderId: '317216724501',
    projectId: 'smart-roll-call-76a46',
    storageBucket: 'smart-roll-call-76a46.firebasestorage.app',
    iosBundleId: 'com.example.smartRollCallFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF1qEoNBVUtCFX07zoHpytvDoPz5KX554',
    appId: '1:317216724501:ios:178e9d2a0435a25f06601c',
    messagingSenderId: '317216724501',
    projectId: 'smart-roll-call-76a46',
    storageBucket: 'smart-roll-call-76a46.firebasestorage.app',
    iosBundleId: 'com.example.smartRollCallFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpJ3D_A6FvWv3E4GReo8cuIIUrEo9aWLc',
    appId: '1:317216724501:web:6569a9194344a3b706601c',
    messagingSenderId: '317216724501',
    projectId: 'smart-roll-call-76a46',
    authDomain: 'smart-roll-call-76a46.firebaseapp.com',
    storageBucket: 'smart-roll-call-76a46.firebasestorage.app',
    measurementId: 'G-VB3076H50Q',
  );

}